# .github/workflows/ci.yml Test 13
name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@seperate-steps
    secrets:
      moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
    with:
      internal_workflow_branch: seperate-steps
